# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [87]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [88]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [89]:
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [90]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [91]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [92]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [93]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [94]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [95]:
x = np.arange(10,50)
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [96]:
x = np.arange(10,50)
x = np.flip(x)
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [97]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [98]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [99]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


In [100]:
x = np.array([1,2,0,0,4,0])
print(np.where(x != 0))

(array([0, 1, 4]),)


In [101]:
x = np.array([1,2,0,0,4,0])
print(np.where(x > 0))

(array([0, 1, 4]),)


In [102]:
x = np.array([1,2,0,0,4,0])
print(np.where(x))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [103]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [104]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [105]:
x = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [106]:
x = np.random.random((3,3,3))
print(x)

[[[0.85517231 0.23928143 0.92360434]
  [0.03593058 0.63134302 0.7242749 ]
  [0.70230778 0.83450588 0.51602313]]

 [[0.06070518 0.93457651 0.48412335]
  [0.34357599 0.12846566 0.96788481]
  [0.75422484 0.74785803 0.42125419]]

 [[0.60112374 0.77602385 0.88531778]
  [0.8901816  0.65845189 0.80276191]
  [0.67157451 0.23722432 0.49415668]]]


In [107]:
x = np.random.randint(0,100,(3,3,3))
print(x)

[[[ 5 34 45]
  [34 87 82]
  [ 3 88 77]]

 [[27 53 39]
  [35 73 83]
  [31 91 79]]

 [[85 89  8]
  [23 66 54]
  [68 64 76]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [108]:
x = np.random.random((10,10))
print("Original Array:")
print(x)
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.1762121  0.74601072 0.37991434 0.81050453 0.31959364 0.72186586
  0.07630588 0.24285973 0.96595779 0.54008505]
 [0.06974258 0.03596799 0.58204202 0.09806317 0.75525342 0.21017871
  0.38450892 0.90427297 0.25409333 0.77938191]
 [0.66916395 0.90795034 0.49578117 0.37240199 0.24847397 0.15716968
  0.34220217 0.98441054 0.04200185 0.98398025]
 [0.77205194 0.32796452 0.23776257 0.23998688 0.32337671 0.64577449
  0.06254133 0.64561318 0.99718405 0.55935865]
 [0.22389821 0.86282578 0.15949991 0.51557805 0.68205461 0.59581318
  0.83424953 0.10333878 0.57557316 0.3762864 ]
 [0.89261542 0.49719969 0.17156732 0.55337837 0.70853995 0.02423531
  0.95986241 0.21334378 0.35316366 0.99571764]
 [0.15403804 0.15212735 0.38609766 0.10753139 0.74742448 0.66719057
  0.89153901 0.44423352 0.34071434 0.17004468]
 [0.59573299 0.56495762 0.31929457 0.37775753 0.07591992 0.5522088
  0.66226425 0.42471252 0.32455879 0.15138285]
 [0.33246241 0.88794574 0.58053475 0.57352637 0.91152979 0.962419

In [109]:
x = np.random.randint(0,100,(10,10))
print("Original Array:")
print(x)
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(f'Minimum: {xmin}, Maximum: {xmax}')

Original Array:
[[62 44 74 66 99 64 55 93 61 75]
 [52 44 61 51 13 33 37 80 23 87]
 [21 44 18 98 58  4 93 94 95 22]
 [73 31 23 83 92 38  0 98 67 72]
 [37 74 32 36 83 40 90 32 73 85]
 [60 34 81 94 49 65 79 66 84 69]
 [67 38 82 20 85 14 42 27 26 87]
 [15 22 77 41 38 70  1 61 66  1]
 [89 21 57 89 69 33 33 47 68 14]
 [30 81  3 66  5 33 74 32 14 19]]
Minimum and Maximum Values:
Minimum: 0, Maximum: 99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [110]:
# x = np.random.random(30)
x = np.random.randint(0,100,30)
print("Original array:")
print(x)
# mean = x.mean()
# print("Mean value of the said array:")
# print(mean)
print(f'Mean value of the said array: {x.mean()}')

Original array:
[ 8 42 95  0 43 39 88 39  4 82 39 99 43 78 61 14 12 53 30 67 46 83 42 13
 16 30 24 77 67 81]
Mean value of the said array: 47.166666666666664


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [111]:
  x = np.ones((5,5))
  print("Original array:")
  print(x)
  print("1 on the border and 0 inside in the array")
  x[1:-1,1:-1] = 0
  print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [112]:
x = np.zeros((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=1)
print(x)

Original array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0 on the border and 1 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [130]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [131]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.insert(x, 0, 0, axis=0)
x = np.insert(x, x.shape[0], 0, axis=0)
x = np.insert(x, 0, 0, axis=1)
x = np.insert(x, x.shape[1], 0, axis=1)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [115]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [116]:
x = np.zeros((5,5))
print("Original array:")
print(x)
print("5x5 matrix with values 1,2,3,4 just below the diagonal:")
x = np.diag([1, 2, 3, 4], k=-1)
print(x)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
5x5 matrix with values 1,2,3,4 just below the diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [117]:
x = np.zeros((5,5))
print("Original array:")
print(x)
print("5x5 matrix with values 1,2,3,4 just below the diagonal:")
x = np.diag(1+np.arange(4), k=-1)
print(x)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
5x5 matrix with values 1,2,3,4 just below the diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [132]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [134]:
checkerboard = (np.indices((8, 8)).sum(axis=0) % 2)
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [137]:
row = np.arange(8) % 2
# print(row)
checkerboard = row ^ row[:, None]   # XOR pattern
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [139]:
pattern = np.array([[0, 1], [1, 0]])
# print(pattern)
checkerboard = np.tile(pattern, (4, 4))
print(checkerboard)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [119]:
print(np.unravel_index(99, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


In [141]:
shape = (6, 7, 8)
flat_index = 99

x = flat_index // (shape[1] * shape[2])
y = (flat_index % (shape[1] * shape[2])) // shape[2]
z = flat_index % shape[2]

print((x, y, z))


(1, 5, 3)


In [143]:
arr = np.arange(6*7*8).reshape(6,7,8)
index = np.argwhere(arr == 99)[0]
print(tuple(index))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [120]:
# x = np.tile(np.array([[0,1],[1,0]]), (1, 1))
# print(x)
x = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [121]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

Original Array:
[[0.5137664  0.64417478 0.67747967 0.7799701  0.27977139]
 [0.26854235 0.45456499 0.97334698 0.96837355 0.24176498]
 [0.82858062 0.6482351  0.96194062 0.37156163 0.91594231]
 [0.9624194  0.9485871  0.42824697 0.58589245 0.84242821]
 [0.9833922  0.20448188 0.64279361 0.97806282 0.30258805]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [122]:
x = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(x)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [123]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [124]:
Z = np.arange(10)
print("Original array:")
print(Z)
Z[(Z > 3) & (Z < 8)] *= -1
print("Array with elements between 3 and 8 negated:")
print(Z)

Original array:
[0 1 2 3 4 5 6 7 8 9]
Array with elements between 3 and 8 negated:
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [125]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [126]:
Z = np.arange(10) # Example integer vector

# Let's test each expression
try:
    print("Z**Z is legal:", Z**Z)
except Exception as e:
    print("Z**Z is illegal:", e)

try:
    print("2 << Z >> 2 is legal:", 2 << Z >> 2)
except Exception as e:
    print("2 << Z >> 2 is illegal:", e)

try:
    print("Z <- Z is legal:", Z <- Z)
except Exception as e:
    print("Z <- Z is illegal:", e)

try:
    print("1j*Z is legal:", 1j*Z)
except Exception as e:
    print("1j*Z is illegal:", e)

try:
    print("Z/1/1 is legal:", Z/1/1)
except Exception as e:
    print("Z/1/1 is illegal:", e)

try:
    # ZZ is not a valid expression in Python or NumPy
    print("ZZ is legal: Check manually, likely illegal")
except Exception as e:
    print("ZZ is illegal:", e)

Z**Z is legal: [        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
2 << Z >> 2 is legal: [  0   1   2   4   8  16  32  64 128 256]
Z <- Z is legal: [False False False False False False False False False False]
1j*Z is legal: [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
Z/1/1 is legal: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
ZZ is legal: Check manually, likely illegal


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [127]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [128]:
# Example float array
Z = np.array([-1.5, -0.8, 0.2, 1.1, 2.9])
print("Original array:")
print(Z)

# Round away from zero
Z_rounded = np.copysign(np.ceil(np.abs(Z)), Z)
print("Rounded away from zero:")
print(Z_rounded)

Original array:
[-1.5 -0.8  0.2  1.1  2.9]
Rounded away from zero:
[-2. -1.  1.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [129]:
# Example arrays
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40, 50, 70])

print("Original arrays:")
print(array1)
print(array2)

# Find common values
common_values = np.intersect1d(array1, array2)
print("Common values between the two arrays:")
print(common_values)

Original arrays:
[ 0 10 20 40 60]
[10 30 40 50 70]
Common values between the two arrays:
[10 40]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)